class PlayerData {
  player = '';
  id = 0;
  position = '';
  age = 0;
  team = '';
  team_logo = '';
  games_played = 0.0;
  games_started = 0.0;
  minutes_played = 0.0;
  field_goals_made = 0.0;
  field_goals_att = 0.0;
  field_goals_pct = 0.0;
  three_pts_made = 0.0;
  three_pts_att = 0.0;
  three_pts_pct = 0.0;
  two_pts_made = 0.0;
  two_pts_att = 0.0;
  two_pts_pct = 0.0;
  eff_fg_pct = 0.0;
  ft_made = 0.0;
  ft_att = 0.0;
  ft_pct = 0.0;
  off_rbds = 0.0;
  def_rbds = 0.0;
  tot_rbds = 0.0;
  assists = 0.0;
  steals = 0.0;
  blocks = 0.0;
  turnovers = 0.0;
  pers_fouls = 0.0;
  points = 0.0;
  exp_fv = 0.0;
  price = 0;
  val_ratio = 0.0;
}

module.exports = PlayerData;
