class TeamOppStats {
  rank = 0;
  team = '';
  games_played = 0.0;
  minutes_played = 0.0;
  points = 0.0;
  rebounds = 0.0;
  assists = 0.0;
  steals = 0.0;
  blocks = 0.0;
  turnovers = 0.0;
  personal_fouls = 0.0;
  def_rebounds = 0.0;
  off_rebounds = 0.0;
  tot_rebounds = 0.0;
  field_goals_made = 0.0;
  field_goals_att = 0.0;
  field_goal_pct = 0.0;
  three_pts_made = 0.0;
  three_pts_att = 0.0;
  three_pt_pct = 0.0;
  two_pts_made = 0.0;
  two_pts_att = 0.0;
  two_pt_pct = 0.0;
  free_throws_made = 0.0;
  free_throws_att = 0.0;
  free_throw_pct = 0.0;
  eff = 0.0;
  deff = 0.0;
}

module.exports = TeamOppStats;
